permalink: /:categories/:title.html
url: "http://bifurcatedtech.com/"
full_name: "Bifurcated Tech"
first_name: "Bifurcated"
last_name: "Tech"
blog_title: "Blog title "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "bifurcatedtech"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "bifurcatedtech"
github: "bifurcatedtech"
facebook: ""
linkined_url: ""
